/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cd_project;

import cd_project.lexer.CustomLexer;
import cd_project.lexer.CustomScanner;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length > 0) {
            try {
                CustomScanner cs = new CustomScanner();
                String fileData = cs.ScanInput(args[0]);
                CustomLexer l = new CustomLexer(fileData);
                l.printTokens();
            } catch(Exception e) {
                CustomLexer.error(-1, -1, "Exception: " + e.getMessage());
            }
        } else {
            CustomLexer.error(-1, -1, "No args");
        }
    }
}
